; XRP Ticker - LilyGo T-Display S3
; https://docs.platformio.org/page/projectconf.html

[platformio]
globallib_dir = lib
default_envs = XRP-T-Display-S3

[env:XRP-T-Display-S3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_filters =
	esp32_exception_decoder
	time
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
build_flags =
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D TDISPLAY_S3=1
lib_deps =
	https://github.com/takkaO/OpenFontRender
	bblanchon/ArduinoJson@^6.21.2
	https://github.com/tzapu/WiFiManager.git#v2.0.16-rc.2
	mathertel/OneButton @ ^2.0.3
