#!/usr/bin/env python3
"""Downloads the coin logos from CoinGecko and writes src/media/logos.h.

Each logo is stored as RGB565 pixels plus an 8-bit alpha mask, so the firmware can blend it on any background.
Dark logos (XRP, XLM) are placed on a white disc so they stay visible on the dark screen.

Usage: pip install pillow && python3 tools/make_logos.py
"""
import io
import pathlib
import urllib.request

from PIL import Image, ImageDraw

# Same order as COINS[] in src/priceService.cpp
COINS = [
    ("XRP", "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png", True),
    ("XLM", "https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg", True),
    ("VELO", "https://coin-images.coingecko.com/coins/images/12538/large/Logo_200x_200.png", False),
]
SIZES = {"LARGE": 64, "MEDIUM": 32, "SMALL": 20}
SUPERSAMPLE = 4
GLYPH_SCALE = 0.78  # Glyph size inside the white disc

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "media" / "logos.h"


def download(url):
    request = urllib.request.Request(url, headers={"User-Agent": "Crypto-Ticker-logo-tool"})
    with urllib.request.urlopen(request) as response:
        return Image.open(io.BytesIO(response.read())).convert("RGBA")


def badge(image, on_disc, size):
    big = size * SUPERSAMPLE
    if on_disc:
        canvas = Image.new("RGBA", (big, big), (255, 255, 255, 0))
        disc = Image.new("L", (big, big), 0)
        ImageDraw.Draw(disc).ellipse((0, 0, big - 1, big - 1), fill=255)
        white = Image.new("RGBA", (big, big), (255, 255, 255, 255))
        canvas.paste(white, (0, 0), disc)
        glyph_size = int(big * GLYPH_SCALE)
        glyph = image.resize((glyph_size, glyph_size), Image.LANCZOS)
        offset = (big - glyph_size) // 2
        canvas.alpha_composite(glyph, (offset, offset))
        # Keep the glyph inside the disc
        canvas.putalpha(Image.composite(canvas.getchannel("A"), disc, disc))
    else:
        canvas = image.resize((big, big), Image.LANCZOS)
    return canvas.resize((size, size), Image.LANCZOS)


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def c_array(ctype, name, values, per_line):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("  " + ", ".join(values[i:i + per_line]) + ",")
    return f"static const {ctype} {name}[] PROGMEM = {{\n" + "\n".join(lines) + "\n};\n"


def main():
    parts = [
        "#ifndef LOGOS_H\n#define LOGOS_H\n\n#include <Arduino.h>\n\n",
        "// Coin logos from CoinGecko, generated by tools/make_logos.py. Do not edit by hand.\n",
        "// RGB565 pixels plus an alpha mask (0 = transparent, 255 = opaque), row by row.\n\n",
    ]
    for label, px in SIZES.items():
        parts.append(f"#define LOGO_{label} {px}\n")
    parts.append("\n")

    for symbol, url, on_disc in COINS:
        source = download(url)
        for label, px in SIZES.items():
            image = badge(source, on_disc, px)
            pixels = [image.getpixel((x, y)) for y in range(px) for x in range(px)]
            colors = [f"0x{rgb565(r, g, b):04X}" for r, g, b, _ in pixels]
            alphas = [f"{a}" for _, _, _, a in pixels]
            parts.append(c_array("uint16_t", f"LOGO_{symbol}_{label}_RGB", colors, 16))
            parts.append(c_array("uint8_t", f"LOGO_{symbol}_{label}_ALPHA", alphas, 24))
            parts.append("\n")

    parts.append("#endif // LOGOS_H\n")
    OUT.write_text("".join(parts))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
